# The HCL AppScan CodeSweep for GitHub extension enables you to check your code on 
# every pull request. Run as a GitHub action, the extension identifies vulnerabilities 
# in changed code with every update. But more than just identifying issues, the HCL 
# AppScan CodeSweep for GitHub extension tells you what you need to know to mitigate 
# issues — before they make it to the main branch.
#
# https://github.com/marketplace/actions/hcl-appscan-codesweep

name: "HCL AppScan CodeSweep GitHub Actions"
on:
    push:
        branches: [ master ]
jobs:
    scan:
        runs-on: windows-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v1
          - name: Run AppScan CodeSweep
            uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
            with:
                asoc_key: ${{secrets.ASOC_KEY}}
                asoc_secret: ${{secrets.ASOC_SECRET}}
    env: 
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
